version: '3.8'

services:
  web:
    image: nginx:alpine
    container_name: e_commerce_website
    ports:
      - "9090:80"
    volumes:
      - ./:/usr/share/nginx/html  
    restart: unless-stopped 



    
